project:
  type: website
  resources: 
    - "assets/Fall-2023-Fundraising-Programs.pdf"
  output-dir: docs

website:
  title: "Emily's Fundraising"
  site-url: 'https://emilysfundraising.com/'
  favicon: "assets/favicon.png"
  navbar:
    pinned: true
    title: false
    logo: "assets/logo_transparent.png"
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: programs/index.qmd
        text: Programs
    smooth-scroll: true
  page-footer:
    center:
      - text: "Email"
        href: mailto:emilycobbfundraising@gmail.com
format:
  html:
    link-external-newwindow: true
    theme: [simplex, simplex-theme.scss]
    css: styles.css
    toc: true

editor: visual

