---
format: 
  html:
    page-layout: full
    anchor-sections: false
---

For over 20 years at Emily's Fundraising, we've helped band, chorus, orchestra and other programs successfully meet their fundraising goals. We understand what truly matters to you -- high-quality products, a personal touch, and a smooth and stress-free process.

<h2 style="text-align:center;">

Testimonials

</h2>

::: specialties
::: card
::: card-header
### "Emily is the go-to for it all."
:::

::: card-body
When it comes to someone who you can trust to help you raise funds to improve the experiences for your students, Emily is the go-to for it all. We have been able to provide hundreds of students more access to great experiences over the years as a result of teaming up with Emily's fundraising.

<br>

*Dr. Marcus Morris, Dorman High School Band*
:::
:::

::: card
::: card-header
### "Families and customers rave about the simplicity... rapid turnaround..."
:::

::: card-body
I have worked with Emily for years, and she provides an excellent experience for me and my students. Families and customers rave about the simplicity of the program and the rapid turnaround. Having both brochure and online components appeals to everyone.

<br>

*Pam Brunson, Laing Chorus.*
:::
:::

::: card
::: card-header
### "Working with Emily for 17 years!"
:::

::: card-body
She has such a love and passion for her clients! Emily goes above and beyond to help a program be as successful as possible when fundraising! She makes raising money fun and easy! Highly recommend her services and products! She is truly a joy to work with!

<br>

*Colleen Marsh, Sevier Middle Band and Strings*
:::
:::

::: card
::: card-header
### "\...First fundraiser\...memorable experience."
:::

::: card-body
What impressed me the most was Emily's infectious enthusiasm for the cause. It created a wonderful atmosphere of excitement among the students and staff, making the fundraising process not only successful but also enjoyable. Being my first fundraiser, I was initially unsure, but Emily's Fundraising made it a memorable experience.

<br>

*Christopher Moore, Irmo Middle Chorus*
:::
:::
:::
